/**
 * Self-contained HTML report renderer (E2.3): ONE file a consultant can send
 * — inline CSS only, zero external requests, zero scripts, an attributions
 * footer, and provenance on every group. ALL text is HTML-escaped and every
 * href is attribute-encoded (page titles/snippets are hostile by default).
 */
import type { SiteAuditReport } from '@lumen-seo/core';
import { UA_VERSION } from '@lumen-seo/core';

export const escapeHtml = (s: string): string =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

/** Attribute-safe URL: escape after refusing non-http(s) schemes (javascript: etc.). */
export const safeHref = (raw: string): string => {
  try {
    const u = new URL(raw);
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return '#blocked';
    return escapeHtml(u.href);
  } catch {
    return '#invalid';
  }
};

export const renderHtml = (report: SiteAuditReport): string => {
  const c = report.summary.countsBySeverity;
  const groups = report.summary.byRule ?? [];
  const rows = groups
    .map(
      (g) => `
      <tr class="sev-${g.severity}">
        <td>${escapeHtml(g.severity)}</td>
        <td>${g.helpUrl === undefined ? escapeHtml(g.ruleId) : `<a href="${safeHref(g.helpUrl)}">${escapeHtml(g.ruleId)}</a>`}</td>
        <td class="num">${g.affectedPages}</td>
        <td>${escapeHtml(g.fixHint ?? 'no fix hint provided')}</td>
        <td class="urls">${g.sampleUrls.map((u) => `<a href="${safeHref(u)}">${escapeHtml(u)}</a>`).join('<br>')}</td>
      </tr>`,
    )
    .join('');
  const pages = report.pages
    .map(
      (p) =>
        `<tr><td><a href="${safeHref(p.url)}">${escapeHtml(p.url)}</a></td><td class="num">${p.status ?? '—'}</td><td class="num">${p.score ?? '—'}</td><td>${
          p.skipped === undefined ? escapeHtml(p.title ?? '') : `skipped (${escapeHtml(p.skipped.reason)})`
        }</td></tr>`,
    )
    .join('');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>lumen audit — ${escapeHtml(String(report.configSnapshot.seed ?? ''))}</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.55 system-ui, sans-serif; margin: 2rem auto; max-width: 60rem; padding: 0 1rem; }
  h1 { font-size: 1.5rem; } h2 { font-size: 1.15rem; margin-top: 2rem; }
  table { border-collapse: collapse; width: 100%; margin-top: .75rem; }
  th, td { text-align: left; padding: .35rem .5rem; border-bottom: 1px solid color-mix(in srgb, currentColor 15%, transparent); vertical-align: top; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .sev-error td:first-child { color: #c0392b; font-weight: 600; }
  .sev-warning td:first-child { color: #b9770e; }
  .sev-info td:first-child { opacity: .8; }
  .urls a { display: inline-block; max-width: 34rem; overflow: hidden; text-overflow: ellipsis; }
  footer { margin-top: 2.5rem; font-size: .85rem; opacity: .75; border-top: 1px solid color-mix(in srgb, currentColor 15%, transparent); padding-top: .75rem; }
  .warn { background: color-mix(in srgb, #b9770e 12%, transparent); padding: .5rem .75rem; border-radius: .4rem; }
</style>
</head>
<body>
<h1>lumen audit — ${escapeHtml(String(report.configSnapshot.seed ?? ''))}</h1>
<p>
  score <strong>${report.summary.score ?? 'n/a'}/100</strong> ·
  ${report.summary.pagesAudited ?? report.pages.length} pages audited${report.summary.pagesSkipped ? `, ${report.summary.pagesSkipped} skipped` : ''} ·
  ${c.error} error / ${c.warning} warning / ${c.info} info ·
  ${escapeHtml(report.startedAt)} → ${escapeHtml(report.completedAt)}
</p>
${report.incomplete ? `<p class="warn">INCOMPLETE run (stopReason: ${escapeHtml(report.stopReason ?? 'unknown')}) — treat every count as a lower bound.</p>` : ''}
<h2>Findings by rule</h2>
${groups.length === 0 ? '<p>No findings.</p>' : `<table><thead><tr><th>severity</th><th>rule</th><th>pages</th><th>fix</th><th>samples</th></tr></thead><tbody>${rows}</tbody></table>`}
<h2>Pages</h2>
<table><thead><tr><th>URL</th><th>status</th><th>score</th><th>title</th></tr></thead><tbody>${pages}</tbody></table>
<footer>
  Generated by lumen v${escapeHtml(UA_VERSION)} — static renderer, no JavaScript, no external requests.
  Provenance: every group links its rule (docs anchor); scores weight error 10 / warning 3 / info 0.
  Data attributions: CrUX field data is CC BY 4.0 (Google); Open PageRank data per its terms;
  Tranco list use requires attribution — see the lumen attributions page.
</footer>
</body>
</html>
`;
};
